### ISSUE TITLE
Auto closing app

### ISSUE THREAD

**Issue by juancer** [prashantgupta24/automatic-mouse-mover#52] opened 2023-11-07 10:23 UTC
Hello, My app is auto closing after x time, I want to know if I have any logs somewhere and check if an app problem o something else finding and killing the process.

MacBook pro, M2 2022, MacOs Sonoma 14.1.

Thanks,

**Comment by prashantgupta24** [comment] 2023-11-07 22:50
Seems like a duplicate of https://github.com/prashantgupta24/automatic-mouse-mover/issues/47. 

One possible option is this script that keeps amm running: https://github.com/prashantgupta24/automatic-mouse-mover/issues/47#issuecomment-1747308387, but other than that I'm still trying to get to the bottom of the issue with sonoma. Will close this issue, stay tuned on the other issue for updates!

**Closed by prashantgupta24** 2023-11-07 22:50 UTC
