### ISSUE TITLE
[Feature] support to set start/stop time

### ISSUE THREAD

**Issue by kakaZhou719** [prashantgupta24/automatic-mouse-mover#61] opened 2024-10-11 10:05 UTC
hi Prashant Gupta,

`automatic-mouse-mover` is a very useful tool, it helps me balance my work and life.  :)

I have an idea,  could we support to set start/stop time.  For example, after 10 pm, it will automatically log out.

Have a nice day ~

**Comment by prashantgupta24** [comment] 2024-10-11 22:28
Thank you for the kind words! Great idea, possible duplicate of https://github.com/prashantgupta24/automatic-mouse-mover/issues/40

**Closed** 2024-10-11 22:33 UTC
Labels: duplicate
